services:

    homepage:
        image: ghcr.io/benphelps/homepage:latest
        container_name: homepage
        ports:
            - "8200:3000"
        volumes:
            - ./app/config:/app/config
            - /var/run/docker.sock:/var/run/docker.sock 
        restart: unless-stopped    

        
