services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permite la detecci칩n autom치tica
      - ./config:/app/config  # Configuraci칩n de Homepage
    ports:
      - "8200:3000"
    restart: unless-stopped
    environment:
      - DOCKER_SOCKET=/var/run/docker.sock  # Permite la monitorizaci칩n de contenedores        
